# <center>Generating a Similarity matrix</center>

##### Loading the required modules

In [ ]:
import ants
import trimesh
import stl
import numpy as np
import vtkplotter as vtk
import os
import pandas as pd
from tqdm import tqdm

import warnings
warnings.filterwarnings(action='ignore')

In [4]:
data_dir=os.getcwd()

files=[i for i in os.listdir(data_dir)]
files.sort()

##### Generating the similarity matrix

In [5]:
file_to_ind={v:i for i,v in enumerate(files)}
file_to_ind

{'VHF_Kidney_L_High.nii.gz': 0,
 'VHF_Kidney_R_High.nii.gz': 1,
 'VHM_Kidney_L_High.nii.gz': 2,
 'VHM_Kidney_R_High.nii.gz': 3}

##### Similarity based on Mean Squares Difference in Intensities

In [6]:
sim_mat=np.zeros((len(file_to_ind),len(file_to_ind)))
sim_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
for i in files:
    img1=ants.image_read(os.path.join(data_dir,i))
    for j in files:
        
#         loading the data as antsimage
        img2=ants.image_read(os.path.join(data_dir,j))
    
        temp=ants.image_similarity(img1,img2,metric_type='MeanSquares')
        sim_mat[file_to_ind[i],file_to_ind[j]]=abs(temp)
        print(f"Similarity between {i[:-12].replace('_Kidney','')} & {j[:-12].replace('_Kidney','')} ==> {abs(temp)}")

Similarity between VHF_L & VHF_L ==> 0.0
Similarity between VHF_L & VHF_R ==> inf
Similarity between VHF_L & VHM_L ==> 0.0727512538433075
Similarity between VHF_L & VHM_R ==> 0.10829870402812958
Similarity between VHF_R & VHF_L ==> inf
Similarity between VHF_R & VHF_R ==> 0.0
Similarity between VHF_R & VHM_L ==> 0.07296775281429291
Similarity between VHF_R & VHM_R ==> 0.10800246894359589
Similarity between VHM_L & VHF_L ==> 0.07292565703392029
Similarity between VHM_L & VHF_R ==> 0.07292565703392029
Similarity between VHM_L & VHM_L ==> 0.0
Similarity between VHM_L & VHM_R ==> 0.15292207896709442
Similarity between VHM_R & VHF_L ==> 0.1086125522851944
Similarity between VHM_R & VHF_R ==> 0.1086125522851944
Similarity between VHM_R & VHM_L ==> 0.1527940034866333
Similarity between VHM_R & VHM_R ==> 0.0


In [8]:
sim_mat

array([[0.        ,        inf, 0.07275125, 0.1082987 ],
       [       inf, 0.        , 0.07296775, 0.10800247],
       [0.07292566, 0.07292566, 0.        , 0.15292208],
       [0.10861255, 0.10861255, 0.152794  , 0.        ]])

In [9]:
print('Metric type: Mean Squares\n')
df=pd.DataFrame(sim_mat,index=[i[:-12].replace('_Kidney','') for i in file_to_ind.keys()],\
                columns=[i[:-12].replace('_Kidney','') for i in file_to_ind.keys()])

# storing the similarity matrix in a csv file
df.to_csv('similarity matrix_meansquares.csv')

df.head()

Metric type: Mean Squares



VHF_L     VHF_R     VHM_L     VHM_R
VHF_L  0.000000       inf  0.072751  0.108299
VHF_R       inf  0.000000  0.072968  0.108002
VHM_L  0.072926  0.072926  0.000000  0.152922
VHM_R  0.108613  0.108613  0.152794  0.000000

##### Similarity based on Correlation

In [11]:
sim_mat=np.zeros((len(file_to_ind),len(file_to_ind)))
sim_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
for i in files:
    img1=ants.image_read(os.path.join(data_dir,i))
    for j in files:
        img2=ants.image_read(os.path.join(data_dir,j))
        temp=ants.image_similarity(img1,img2,metric_type='Correlation')
        sim_mat[file_to_ind[i],file_to_ind[j]]=abs(temp)
        print(f"Similarity between {i[:-12].replace('_Kidney','')} & {j[:-12].replace('_Kidney','')} ==> {abs(temp)}")

Similarity between VHF_L & VHF_L ==> 1.0
Similarity between VHF_L & VHF_R ==> 2.0714729931370357e-10
Similarity between VHF_L & VHM_L ==> 0.0
Similarity between VHF_L & VHM_R ==> 0.0
Similarity between VHF_R & VHF_L ==> 6.871126445595621e-10
Similarity between VHF_R & VHF_R ==> 1.0
Similarity between VHF_R & VHM_L ==> 0.0
Similarity between VHF_R & VHM_R ==> 0.0
Similarity between VHM_L & VHF_L ==> 0.0
Similarity between VHM_L & VHF_R ==> 0.0
Similarity between VHM_L & VHM_L ==> 1.0
Similarity between VHM_L & VHM_R ==> 0.003166231792420149
Similarity between VHM_R & VHF_L ==> 0.0
Similarity between VHM_R & VHF_R ==> 0.0
Similarity between VHM_R & VHM_L ==> 0.003174081677570939
Similarity between VHM_R & VHM_R ==> 1.0


In [13]:
sim_mat

array([[1.00000000e+00, 2.07147299e-10, 0.00000000e+00, 0.00000000e+00],
       [6.87112645e-10, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.16623179e-03],
       [0.00000000e+00, 0.00000000e+00, 3.17408168e-03, 1.00000000e+00]])

In [14]:
print('Metric type: Correlation\n')
df=pd.DataFrame(sim_mat,index=[i[:-12].replace('_Kidney','') for i in file_to_ind.keys()],\
                columns=[i[:-12].replace('_Kidney','') for i in file_to_ind.keys()])

# storing the similarity matrix in a csv file
df.to_csv('similarity matrix_correlation.csv')

df.head()

Metric type: Correlation



VHF_L         VHF_R     VHM_L     VHM_R
VHF_L  1.000000e+00  2.071473e-10  0.000000  0.000000
VHF_R  6.871126e-10  1.000000e+00  0.000000  0.000000
VHM_L  0.000000e+00  0.000000e+00  1.000000  0.003166
VHM_R  0.000000e+00  0.000000e+00  0.003174  1.000000